language: fr  # your two-letter language code
pipeline:
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer # Sparce
   - name: LexicalSyntacticFeaturizer # Support Entity extraction
#   - name: CRFEntityExtractor
   - name: CountVectorsFeaturizer # Sparse (BOW)
#     OOV_token: "_oov_"
   - name: CountVectorsFeaturizer # Sparse (characters) -> For Misspellings
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
#     tensorboard_log_directory: 'tensorboard_DIETClassifier'
   - name: EntitySynonymMapper
   - name: ResponseSelector # FAQ retrieval model // The prediction of this model is used by the dialogue manager to utter the predicted responses.
     epochs: 100
     retrieval_intent: faq
   - name: ResponseSelector # Chitchat retrieval model
     epochs: 100
     retrieval_intent: chitchat
#   - name: ResponseSelector
#     retrieval_intent: out_of_scope # out_of_scope retrieval model
#     scale_loss: false
#     epochs: 100
   - name: FallbackClassifier
     threshold: 0.5


policies:
  - name: TEDPolicy # Features: user input (intent and entities), previous system actions, slots and active forms
    max_history: 5
    epochs: 100
    tensorboard_log_directory: 'tensorboard_TEDPolicy' # tensorboard --logdir tensorboard_TEDPolicy
  - name: AugmentedMemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.5
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True